# Generated by Django 3.1.1 on 2020-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jop_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='post_img/')),
                ('published', models.DateTimeField()),
                ('Vacanacy', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('Experiencse', models.IntegerField()),
            ],
        ),
    ]
