# Generated by Django 3.1.1 on 2020-09-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jop.categorys'),
            preserve_default=False,
        ),
    ]
