# Generated by Django 3.1.1 on 2020-09-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0003_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jop',
            name='image',
            field=models.ImageField(upload_to='jobs_img/'),
        ),
    ]
