# Generated by Django 3.1.1 on 2020-09-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0005_aplly'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplly',
            name='jobs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jop.jop', verbose_name='aplly_jop'),
            preserve_default=False,
        ),
    ]
