# Generated by Django 3.1.1 on 2020-09-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0006_aplly_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jop',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Aplly',
        ),
    ]
