# Generated by Django 3.1.1 on 2020-09-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0007_auto_20200919_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_job', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=99)),
                ('website', models.URLField()),
                ('cover_letter', models.TextField(max_length=500)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jop.jop', verbose_name='aplly_jop')),
            ],
        ),
    ]
