# Generated by Django 3.1.1 on 2020-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0008_aplly'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplly',
            name='cv_job',
            field=models.FileField(default='', upload_to='aplly/'),
            preserve_default=False,
        ),
    ]
